let's load dataset first

In [2]:
import pandas as pd

In [3]:
# loading a fake dataset
df = pd.read_parquet(r"D:\coding\assignment-mini-project-\taxi_assingment\data_files\data.parquet")

print(df.head())

df.shape

df.head()

               model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3

   carb
0     4
1     4
2     1
3     1
4     2

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [5]:
# loading project dataset

df = pd.read_parquet(r"D:\coding\assignment-mini-project-\taxi_assingment\data_files\yellow_tripdata_2026-01.parquet")

print(df.head(3))

print("shape of the dataset is", df.shape)

print("columns in the dataset are", df.columns)

print("data types of the dataset are\n", df.dtypes)

df.head(3)

# let's same it as a csv file
# df.to_csv(r"D:\coding\assignment-mini-project-\taxi_assingment\data_files\yellow_tripdata_2026-01.csv", index=False)

   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         2  2026-01-01 00:54:04   2026-01-01 00:59:37              1.0
1         1  2026-01-01 00:34:04   2026-01-01 00:39:47              0.0
2         1  2026-01-01 00:57:06   2026-01-01 01:05:59              0.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           0.97         1.0                  N           239           238
1           0.90         1.0                  N           163           162
2           1.40         1.0                  N            43           237

   payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0             1          7.2   1.00      0.5        3.66           0.0
1             2          7.9   4.25      0.5        0.00           0.0
2             1         10.7   4.25      0.5        2.50           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         15.86                   2.5          0.0
1                    1.0         13.65                   2.5          0.0
2                    1.0         18.95                   2.5          0.0

   cbd_congestion_fee
0                0.00
1                0.75
2                0.75
shape of the dataset is (3724889, 20)
columns in the dataset are Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')
data types of the dataset are
 VendorID                          int32
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int32
DOLocationID                      int32
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
Airport_fee                     float64
cbd_congestion_fee              float64
dtype: object

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75

In [6]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'cbd_congestion_fee'],
      dtype='object')

In [ ]:

for col in ['tpep_pickup_datetime', 'tpep_dropoff_datetime']:
    df[col] = pd.to_datetime(df[col], errors='coerce')

# Create a new duration column
df['trip_duration'] = (df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']).dt.total_seconds() / 60


initial_rows = len(df)
valid_columns = [
    'tpep_pickup_datetime',
    'tpep_dropoff_datetime',
    'passenger_count',
    'trip_distance',
    'fare_amount',
    'total_amount',
    'trip_duration'
]
df = df.dropna(subset=valid_columns)

df = df[
    (df['trip_duration'] > 0) &
    (df['trip_distance'] > 0) &
    (df['passenger_count'] >= 1) &
    (df['fare_amount'] >= 0) &
    (df['total_amount'] >= 0)
]


duration_max = df['trip_duration'].quantile(0.99)
distance_max = df['trip_distance'].quantile(0.99)
fare_max = df['fare_amount'].quantile(0.99)
total_max = df['total_amount'].quantile(0.99)

df = df[
    (df['trip_duration'] <= duration_max) &
    (df['trip_distance'] <= distance_max) &
    (df['fare_amount'] <= fare_max) &
    (df['total_amount'] <= total_max)
]

cleaned_rows = len(df)
print(f"Rows before cleaning: {initial_rows}")
print(f"Rows after cleaning: {cleaned_rows}")
print(f"Dropped rows: {initial_rows - cleaned_rows}")
print("Current columns:", df.columns.tolist())
print("Trip duration range (min,max):", df['trip_duration'].min(), df['trip_duration'].max())


df.head()

Rows before cleaning: 3724889
Rows after cleaning: 2444739
Dropped rows: 1280150
Current columns: ['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'Airport_fee', 'cbd_congestion_fee', 'trip_duration']
Trip duration range (min,max): 0.016666666666666666 78.1

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,trip_duration
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,...,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00,5.550000
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,...,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75,42.800000
5,2,2026-01-01 00:47:11,2026-01-01 01:00:47,2.0,2.33,1.0,N,144,137,1,...,1.00,0.5,4.99,0.0,1.0,24.94,2.5,0.0,0.75,13.600000
6,1,2026-01-01 00:17:54,2026-01-01 00:28:32,1.0,1.30,1.0,N,142,50,2,...,4.25,0.5,0.00,0.0,1.0,17.15,2.5,0.0,0.75,10.633333
8,2,2026-01-01 00:34:14,2026-01-01 01:11:58,1.0,5.34,1.0,N,161,45,1,...,1.00,0.5,8.61,0.0,1.0,51.66,2.5,0.0,0.75,37.733333

In [9]:
df.describe()

df.isnull().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
Airport_fee              0
cbd_congestion_fee       0
trip_duration            0
dtype: int64